workflows:
  android-apk:
    name: Build Android APK
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        JAVA_VERSION: 11
    scripts:
      - name: Check and use gradlew if present
        script: |
          if [ -f "./gradle/wrapper/gradle-wrapper.jar" ]; then
            echo "gradle-wrapper.jar found. Making gradlew executable..."
            chmod +x ./gradlew
            ./gradlew assembleDebug
          else
            echo "gradle-wrapper.jar not found. Falling back to system Gradle..."
            gradle assembleDebug
          fi
    artifacts:
      - app/build/outputs/**/*.apk
