workflows:
  android-apk:
    name: Build Android APK
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        JAVA_VERSION: 11
    scripts:
      - name: Build APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
