workflows:
  android-apk:
    name: Build Android APK
    max_build_duration: 15
    environment:
      android_signing:
        - keystore_reference
      vars:
        JAVA_VERSION: 11
    scripts:
      - name: Build APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
